services:
  scatter:
    build: .
    container_name: blender-scatter-ci
    volumes:
      - /tmp/blender-4.2.0-linux-x64:/opt/blender
      - .:/app
    environment:
      - BLENDER_PATH=/opt/blender
